# Travis-CI ~ PHP + Node.JS.

language: php

php:
  # - 7.0
  - 7.1

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache/files # PHP packages
    - node_modules # NPM packages

before_install:
  - nvm install v8.1
  - node -v && npm -v

install:
  - composer install
  - npm install

before_script:
  - composer build
  - npm run build

script:
  - composer validate --no-interaction
  - composer test
  - composer hook pre-commit
  - npm test
  #- node tests/test.js
  - composer execute

after_script:
  - npm run pa11y-ci
  - ls -alh
  - cat .git/hooks/pre-commit
  #- git status

# End.
